drupal/dh_wsp/plugins/dh_variables/dHVwudsMpVars.class.php
- dHMonthlyFractionFactors updated to store facility monthly fractions matrix in 2-column format
=> dHVwudsMpVars.class.php updates 

R/wsp/wsp2020/FoundationDataset/foundation2_demand_projections.R
=> foundation3

R/wsp/wsp2020/FoundationDataset/foundation2_demand_projections.R, R/wsp/wsp2020/FoundationDataset/geo_summaries/Foundation-add-containing-features.R
-minor basins added to mp.all foundation dataset
-facility coordinates added to foundation2
=> 2.28.2020 mp.all.minor.basins

R/wsp/wsp2020/FoundationDataset/geo_summaries/minor_basin_summary_maps.R, R/wsp/wsp2020/FoundationDataset/geo_summaries/shenandoah_single_basin_summary_maps.R, R/wsp/wsp2020/FoundationDataset/geo_summaries/single_basin_model_maps/base_model_mb_map.R, R/wsp/wsp2020/FoundationDataset/geo_summaries/single_basin_model_maps/current_11_to_13.R, R/wsp/wsp2020/FoundationDataset/geo_summaries/single_basin_model_maps/exempt_11_to_18.R, R/wsp/wsp2020/FoundationDataset/geo_summaries/single_basin_model_maps/p10_11_to_15.R, R/wsp/wsp2020/FoundationDataset/geo_summaries/single_basin_model_maps/p90_11_to_16.R, R/wsp/wsp2020/FoundationDataset/geo_summaries/statewide_summary_maps.R, R/wsp/wsp2020/minor_basin_latex.R
-new folder called single_basin_model_maps
-shenandoah_single_basin_summary_maps.R still has Top5 and all_points maps that need to be moved over to new base_model_mb_map
=> restructured single basin model summary maps

R/wsp/wsp2020/FoundationDataset/geo_summaries/minorbasin.mapgen.R, R/wsp/wsp2020/FoundationDataset/geo_summaries/minorbasin_maps.R
Several Updates
- pulled mapping code into a separate function file minorbasin.mapgen.R
- minorbasin_maps.R now calls the function above
- code now using "folder" as declared in config.local.private
- prevented error in mapping code by removing duplicate hydrocode column
- updated ggsave() to utilize "export_path" 
- updated output filenames to use "JA_" naming convention
- revised function inputs
- made loop through multiple minor basins more robust
=> Created separate function minorbasin.mapgen()

R/wsp/wsp2020/FoundationDataset/geo_summaries/mb.extent.R, R/wsp/wsp2020/FoundationDataset/geo_summaries/minorbasin.mapgen.R, R/wsp/wsp2020/FoundationDataset/geo_summaries/minorbasin_maps.R
- Updated to overlay FIPS names from VAHydro layer
- Updated to use tile satellite base map
- Code cleaned up, mb.extent() function created
=> minor basin mapping updates

R/wsp/wsp2020/FoundationDataset/geo_summaries/minorbasin.mapgen.R, R/wsp/wsp2020/FoundationDataset/geo_summaries/minorbasin.mapgen.SINGLE.SCENARIO.R, R/wsp/wsp2020/FoundationDataset/geo_summaries/minorbasin_maps.R
Updates: 
- Now plotting intake locations/demands only (not showing wells)
- Updated to show all intakes (not filtering out power facilities)
- Moved demand legend to left of map, updated legend label - is now dynamic based on model scenario
- Increased size of rseg legend
- Changed color of rseg borders to black
=> Several Mapping Updates

R/wsp/wsp2020/FoundationDataset/geo_summaries/minorbasin.mapgen.R, R/wsp/wsp2020/FoundationDataset/geo_summaries/minorbasin_maps.R
- All legends moved to right of map window
- Demand legend condensed
- Well & Intake Source Locations map - symbols updated to purple bubbles and green triangles of uniform size
=> Legend and demand points updates

R/wsp/wsp2020/FoundationDataset/geo_summaries/minorbasin.mapgen.R, R/wsp/wsp2020/FoundationDataset/geo_summaries/minorbasin_maps.R
-  Margins adjusted for improved map window fit within image
=> Plot margins improved

R/wsp/wsp2020/FoundationDataset/geo_summaries/minorbasin.mapgen.R, R/wsp/wsp2020/FoundationDataset/geo_summaries/minorbasin_maps.R
- Updated color scale (Darkest color swapped with second-darkest)
=> Updated color scale

R/wsp/wsp2020/FoundationDataset/geo_summaries/minorbasin.mapgen.R, R/wsp/wsp2020/FoundationDataset/geo_summaries/minorbasin.mapgen.SINGLE.SCENARIO.R, R/wsp/wsp2020/FoundationDataset/geo_summaries/minorbasin_maps.R
- minorbasin.mapgen.SINGLE.SCENARIO updated to match minorbasin.mapgen style
=> Aesthetic Improvements

R/wsp/wsp2020/FoundationDataset/geo_summaries/minorbasin.mapgen.R, R/wsp/wsp2020/FoundationDataset/geo_summaries/minorbasin_maps.R
- IFIM sites added to Minor Basin "Well & Intake Source Locations" maps
=> ifim site locations

R/wsp/wsp2020/FoundationDataset/geo_summaries/statewide.mapgen.R, R/wsp/wsp2020/FoundationDataset/geo_summaries/statewide.mapgen.SINGLE.SCENARIO.R, R/wsp/wsp2020/FoundationDataset/geo_summaries/statewide_maps.R
- Updated scale to include green "bins" for positive increases, and +/- 5% bin for "no change"
- Updated overall % of flow change legend to use negatives "-" for decreases
=> Updated Statewide Maps

R/wsp/wsp2020/FoundationDataset/geo_summaries/minorbasin.mapgen.R, R/wsp/wsp2020/FoundationDataset/geo_summaries/minorbasin.mapgen.SINGLE.SCENARIO.R, R/wsp/wsp2020/FoundationDataset/geo_summaries/minorbasin_maps.R, R/wsp/wsp2020/FoundationDataset/geo_summaries/statewide.mapgen.R, R/wsp/wsp2020/FoundationDataset/geo_summaries/statewide.mapgen.SINGLE.SCENARIO.R, R/wsp/wsp2020/FoundationDataset/geo_summaries/statewide_maps.R
- Major reservoirs layer added to all maps 
- Rseg border color lightened in all VA statewide maps
=> Reservoirs

R/wsp/wsp2020/FoundationDataset/geo_summaries/map.divs.R, R/wsp/wsp2020/FoundationDataset/geo_summaries/minorbasin.mapgen.R, R/wsp/wsp2020/FoundationDataset/geo_summaries/minorbasin.mapgen.SINGLE.SCENARIO.R, R/wsp/wsp2020/FoundationDataset/geo_summaries/minorbasin_maps.R, R/wsp/wsp2020/FoundationDataset/geo_summaries/statewide.mapgen.R, R/wsp/wsp2020/FoundationDataset/geo_summaries/statewide.mapgen.SINGLE.SCENARIO.R, R/wsp/wsp2020/FoundationDataset/geo_summaries/statewide_maps.R
Various Updates:
- Passing in legend_colors and legend_divs
- All "0000" segments grayed out (Including those rsegs that flow into surrounding states)
- Duplicate hydrocode column issue resolved
=> Divs Updates 2.0

drupal/dh_drought/src/r/USGS_drought_flow.R, drupal/dh_drought/src/r/USGS_drought_gwl.R
1) 7day rolling average generated using ANY available data from past 7 days (No longer breaks with NAs)
2) Uses monthly percentiles by looking at “what month yesterday was in”
=> Drought Code Updates

R/data management/data_swap_via_REST.R
#ISSUE QUEUE https://gitlab.deq.virginia.gov/VAHydro/VAHydro/-/issues/79 - GW0002201 Woods Edge DATA SWAP
=> Data management data swap

R/examples/VWP_CIA_Summary.Rmd
- Updated to automate insertion of unmet demand heatmap plots 
- Updated to automate insertion of elfgen plot 
- Additional aesthetic improvements
=> Rmd Updates

R/examples/VWP_CIA_Summary_BSG.Rmd
Retrieve JK's changes from CIA doc.
=> Get JK changes

R/examples/VWP_CIA_Summary.Rmd, R/permitting/Salem WTP/run_om_model_table.R
Allows greater flexibility in producing tables of summary stats for both rseg and facility models -> table now displays rseg withdrawal and point source in addition to cumulative withdrawal and cumulative point source
=> Updated Rmd to use om_model_table()

R/permitting/Salem WTP/salem.R, sh/setup_postgres_crontab.sh
@jdkleiner FYI I added that Salem R  file from the other day.
=> new Salem file, finally figured out crontab to run after startup

R/examples/VWP_CIA_Summary.Rmd
- Rmd updated to use the FDC and hydrograph plots generated in automated summary script
=> Rmd template plot updates

R/examples/VWP_CIA_Summary.Rmd
=> consumption table percent values on new line

R/AnnualReporting/AWRR_data.R
Replaced for loop with calls of sapply.
Now succinct
=> Updated AWRR fac_all section

R/OWS_summaries/model_run_brief.Rmd
also removed openmi.om library load because it is not used?
=> use is.logical not boolean

drupal/dh_drought/src/r/summary_map/drought_map_dependencies/base.map.R, drupal/dh_drought/src/r/summary_map/virginia_drought_indicators_map.R
Removed reference to stamen maps. Now does not pull in any basemap, hence the white background
=> Updated the drought indicator map.

R/AnnualReporting/AWRR_data.R
Some confusion with branch name and commits. The purpose of this pull request was to format the sqldf statements and replace the periods in column names with underscores.
=> Updating formatting and names in AWRR_data.R
